### ISSUE TITLE
Configuration method for prompt=select_account

### ISSUE THREAD

**Issue by linhdangduy** [doorkeeper-gem/doorkeeper-openid_connect#107]
### Problem
With `prompt=login`, we have the [reauthenticate_oidc_resource_owner](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/v1.7.1/lib/doorkeeper/openid_connect/helpers/controller.rb#L64-L65) method to call the config [reauthenticate_resource_owner](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/v1.7.1/lib/doorkeeper/openid_connect/config.rb#L112-L114). So user just have to defined some code in `reauthenticate_resource_owner` in doorkeeper_openid_connect.rb to execute the code as user's need.

Why doorkeeper oidc don't have the equivalent config when `prompt=select_account`?
https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/master/lib/doorkeeper/openid_connect/helpers/controller.rb#L68-L71
If possible could we add config function for `select_account`?

### Currently behavior
Because the gem only write that:
```ruby
when 'select_account'
  # TODO: let the user implement this
  raise Errors::AccountSelectionRequired
```
the error is rescued at [here](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/v1.7.1/lib/doorkeeper/openid_connect/helpers/controller.rb#L14-L16). So to be able to use `prompt=select_account`, I see that user have to monkey-patch the [handle_oidc_prompt_param!](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/v1.7.1/lib/doorkeeper/openid_connect/helpers/controller.rb#L55) method as following:
```ruby
def handle_oidc_prompt_param!(owner)
  super(owner)
rescue Errors::AccountSelectionRequired
  # user's defined select_account behavior  
end
```
that not clean, hard to maintain for user.

### Expect
```ruby
when 'select_account'
  call_select_account_config(owner) # execute the config for select_account
```

What do you think about this idea?

**Comment by toupeira** [comment]
@linhdangduy that's a great question, I don't remember what I had in mind when I originally wrote this :sweat_smile: 

But yes I think adding configuration for this makes sense! :+1: 

In the default proc we could raise `Errors::InvalidConfiguration` as the others do, and get rid of `Errors::AccountSelectionRequired`.

Do you want to submit a PR?

**Comment by toupeira** [comment]
@linhdangduy oh and BTW there's potential for name clashes in `Doorkeeper::OpenidConnect::Helpers::Controller` because it's included in other controllers, so I propose we call the method there something like `select_account_for_oidc_resource_owner` and the configuration value maybe `select_account_for_resource_owner`, receiving the `owner` as only argument? Happy with other names too, just the method in the helper should include `oidc` somewhere.

**Comment by linhdangduy** [comment]
@toupeira Thank for your attention. I'm happy to propose a PR!
