### ISSUE TITLE
Support Doorkeeper 5.5.0

### ISSUE THREAD

**Issue by pjmartorell** [doorkeeper-gem/doorkeeper-openid_connect#141]
`doorkeeper` has some deprecation warnings when running it with ruby 2.7 and they are fixed on Doorkeeper 5.5.0 but the gemspec of `doorkeeper-openid_connect` is not allowing `doorkeeper` 5.5.0:
https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/805b7ca9c42a011e357b2d6daac88c45e7f2172a/doorkeeper-openid_connect.gemspec#L27

Do you know if there is any change in doorkeeper 5.5.0 that breaks `doorkeeper-openid_connect`? if not, could we support doorkeeper 5.5.0?

Thanks

**Comment by toupeira** [comment]
Doorkeeper 5.5 should be supported now with https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/138, so I'll go ahead and close this.

Will cut a new 1.8.0 release shortly...
