### ISSUE TITLE
fix issuer {} for `.well-known/openid-configuration` using blocks

### ISSUE THREAD

**Issue by fkowal** [doorkeeper-gem/doorkeeper-openid_connect#160]
#144 when using a block to configure the `issuer`

`app/controllers/doorkeeper/openid_connect/discovery_controller.rb` returns `{}`

FYI

I am a total ruby noob, so the following PR will raise a lot of eyebrows

**Comment by nbulaj** [comment]
#161 merged and released, thanks!
