### ISSUE TITLE
`access_grant_class` is broken.

### ISSUE THREAD

**Issue by Exterm1nate** [doorkeeper-gem/doorkeeper-openid_connect#174]
### Steps to reproduce

```ruby
# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  access_grant_class "Oauth::AccessGrant"
end

# app/models/oauth/access_grant.rb
require "doorkeeper/orm/active_record/mixins/access_grant"

module Oauth
  class AccessGrant < ActiveRecord::Base
    include ::Doorkeeper::Orm::ActiveRecord::Mixins::AccessGrant

  end
end
```

When starting application an error occures:

```
NameError: uninitialized constant Oauth
    Object.const_get(camel_cased_word)
```

I tried to require model in the initializer and the error changed:

```
Doorkeeper::MissingConfiguration: Configuration for doorkeeper missing. Do you have doorkeeper initializer?
```

With other two classes (`access_token_class`, `application_class`) application starts correctly. 
Seems that lib/doorkeeper/openid_connect/orm/active_record.rb:35 is not working.

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.2

**Doorkeeper version**: 5.5.4

**Doorkeeper OpenID version**: 1.8.2

**Comment by nbulaj** [comment]
Thanks for reporting this!

Could be related to @nov changes here https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/168, I'll take a look closer a little bit later

**Comment by Exterm1nate** [comment]
I debuged my application and came to the conclusion that the problem is in the Sorcery gem. 
Updated your sample app to demonstrate it.
https://github.com/Exterm1nate/doorkeeper-openid_connect-sample

**Comment by nov** [comment]
Ah, because you have `oauth` gem, `OAuth` is already defined...

**Comment by Exterm1nate** [comment]
It doesn't matter what class is provided.

The same issue for any other model, without `Oauth` namespace.
```ruby
Doorkeeper.configure do
  access_grant_class "ApplicationRecord"
end
```

**Comment by nov** [comment]
It seems because of Sorcery bug, which should be fixed in Sorcery v1.
https://github.com/Sorcery/sorcery/issues/316
https://github.com/Sorcery/sorcery/issues/312#issuecomment-1130370988

Does doorkeeper-openid_connect need some changes?
