### ISSUE TITLE
OpenID working with rails app

### ISSUE THREAD

**Issue by tb582** [doorkeeper-gem/doorkeeper-openid_connect#190]
Anyone got this combo working?? 

```
    doorkeeper (5.6.4)
    doorkeeper-openid_connect (1.8.5)
      doorkeeper (>= 5.5, < 5.7)
```

I keep getting

```
`block in <top (required)>': undefined method `openid_configuration' for #<Doorkeeper::Config::Builder:0x0000000108e4ca88 @config=#<Doorkeeper::Config:0x0000000108e4c9e8 @optional_scopes=#<Doorkeeper::OAuth::Scopes:0x0000000108e55f98 @scopes=["openid"]>, @default_scopes=#<Doorkeeper::OAuth::Scopes:0x0000000108e55d90 @scopes=["read"]>, @authenticate_resource_owner=#

  openid_configuration do
```

my doorkeeper.rb file::

```
require 'doorkeeper/openid_connect'

Doorkeeper.configure do
  optional_scopes :openid
  default_scopes :read
  resource_owner_authenticator do
    if params[:current_user].present?
      User.find(params[:current_user])
    else
      redirect_to('/login')
      nil
    end
    enforce_configured_scopes
  end

  grant_flows %w[authorization_code client_credentials implicit_oidc]

  # OpenID Connect configuration
  openid_configuration do
    issuer 'dummy'
    subject_types_supported [:public]
    response_types_supported [:code]
    jwks_uri '<removed>'

    # Specify the OpenID Connect provider endpoint URLs
    authorization_endpoint '<removed>'
    token_endpoint '<removed>'
  end
end

```

**Comment by nbulaj** [comment]
Hey @tb582 

What is `openid_configuration` inside Doorkeeper configuration? :thinking: We don't have such option (even in the repo https://github.com/doorkeeper-gem/doorkeeper-openid_connect/search?q=openid_configuration )

But you must have something like this:

```ruby
# config/initializers/doorkeeper_openid_connect.rb
Doorkeeper::OpenidConnect.configure do
  # ...
end
```

**Comment by nbulaj** [comment]
Also `enforce_configured_scopes` config option shouldn't be inside `resource_owner_authenticator` block, but maybe you just copied it wrong

**Comment by tb582** [comment]
hmm are there working configs of both 

doorkeeper_openid_connect.rb

and 

doorkeeper.rb

**Comment by nbulaj** [comment]
Hey, not sure I understood your question. You can find config examples both for [Doorkeeper](https://doorkeeper.gitbook.io/guides/ruby-on-rails/configuration) and [OpenID Connect](https://github.com/doorkeeper-gem/doorkeeper-openid_connect#configuration)

**Comment by nbulaj** [comment]
OK closing this one as it has invalid configurations. Please see examples above and in the projects README / Wiki
