### ISSUE TITLE
Missing v1.8.5 tag

### ISSUE THREAD

**Issue by stanhu** [doorkeeper-gem/doorkeeper-openid_connect#196]
https://rubygems.org/gems/doorkeeper-openid_connect has v1.8.5, but this repository doesn't have the v1.8.5 tag. Would you mind adding the tag?

**Comment by stanhu** [comment]
Looks like v1.8.5 is up. Thanks!

**Comment by nbulaj** [comment]
Sorry forgot to reply. Done, thanks 🤝
