### ISSUE TITLE
NameError: uninitialized constant Doorkeeper::JWT::JWK

### ISSUE THREAD

**Issue by michael-cybrid** [doorkeeper-gem/doorkeeper-openid_connect#197]
### Issue

* Getting `NameError: uninitialized constant Doorkeeper::JWT::JWK` when calling `as_jws_token` on `Doorkeeper::OpenidConnect::IdToken`
* This was introduced in https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/194 by @stanhu with the line `::JWT::JWK.new(key, { kid_generator: JWT::JWK::Thumbprint })`

### Possible Fix

* That line should instead be `::JWT::JWK.new(key, { kid_generator: ::JWT::JWK::Thumbprint })`

**Comment by stanhu** [comment]
Submitted #198. 

What Ruby version are you using by chance? I wasn't able to reproduce this on Ruby 3.0 or 3.1, and we've had this code running in production for over a month.

**Comment by michael-cybrid** [comment]
Sorry, didn't see this response; I am using `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]`.

**Comment by stanhu** [comment]
🤷 Ruby 3.2.2 passes for me locally as well. 

@nbulaj Could you look at #198?

**Comment by nbulaj** [comment]
Sorry, github closes automatically. 

@michael-cybrid could you please install the master branch of the gem and check if everything is OK? I will release then in case of success

**Comment by michael-cybrid** [comment]
Verified; the fix works. Thanks!

**Comment by nbulaj** [comment]
Released with 1.8.7, thanks
