### ISSUE TITLE
Release version 1.0.3

### ISSUE THREAD

**Issue by chrisblatchley** [doorkeeper-gem/doorkeeper-openid_connect#23]
Hello @toupeira, great work getting this gem cleaned up after the change in ownership. I was wondering what issues are in the way of releasing version 1.0.3? I've integrated it locally, and it seems to work as expected, but don't think I wanna ship it with a github link in the gem file :)

Sorry if this is a weird place for this question, I'm not sure how else to ask this.

**Comment by toupeira** [comment]
@chrisblatchley thanks, good to hear I didn't break anything yet!

I was actually planning to release 1.1.0 soon and was still waiting on feedback on some Doorkeeper issues, but they're pretty minor so I think I'll just go ahead with the release and add some caveats to the README. Should be up soon!

**Comment by chrisblatchley** [comment]
Thank you! That will be super helpful.

**Comment by toupeira** [comment]
@chrisblatchley ok the release is ready but I still need permissions to push the gem. The current owner is listed as `ops@playonsports.com`, can you find somebody with access to that account and tell them to run `gem owner doorkeeper-openid_connect --add markus-koller@gmx.ch`? Your account will still be an owner as well, see `gem owner doorkeeper-openid_connect`. Thanks!

**Comment by chrisblatchley** [comment]
oh sorry, I'm not affiliated with playonsports.com. I'm surprised they didn't do that when transferring ownership.

**Comment by playon-readonly** [comment]
We will work on the transfer today.

**Comment by toupeira** [comment]
@chrisblatchley whoops I'm sorry, I just somehow assumed you were because you mentioned the transfer in ownership :)

@playon-readonly thanks, much appreciated!

**Comment by playon-readonly** [comment]
markus-koller@gmx.ch<mailto:markus-koller@gmx.ch> has now been added as an owner of the gem.

**Comment by toupeira** [comment]
@playon-readonly thanks!

@chrisblatchley 1.1.0 is released! 🍾 

I added [upgrade instructions](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/master/CHANGELOG.md#upgrading) to the CHANGELOG, let me know if you run into any problems!
