### ISSUE TITLE
Integrating with Devise/Warden flows

### ISSUE THREAD

**Issue by malacalypse** [doorkeeper-gem/doorkeeper-openid_connect#24]
Hello, this isn't an issue per se, it's more of an integration question.

We're interested in using this along with our web sessions to authenticate a user against our Devise framework (which, of course, uses Warden in the background). Our team has some experience with oAuth and other authentication protocols, but none in particular with OpenID Connect and rails app integration.

The main questions are:

1. Is something like the [warden-doorkeeper gem](https://github.com/kolorahl/warden-doorkeeper) the best solution to begin integrating these, or can it be more simply done?
2. Is it possible to use existing session state if the user is already logged in?
3. Which part of this is responsible for rendering the view wherein the user (post-authentication) is presented with the requested scopes/claims and accepts or rejects the authorization request?

Finally, is a migration on the user to store some sort of subject identifier required or is there a property on the user object provided by doorkeeper already that can be coopted into this role?

Thank you very much!

**Comment by toupeira** [comment]
> Is something like the warden-doorkeeper gem the best solution to begin integrating these, or can it be more simply done?

I'm not familiar with this gem but it looks to be [just a bit of glue around Doorkeeper](https://github.com/kolorahl/warden-doorkeeper/blob/master/lib/warden/strategies/doorkeeper.rb).

Setting this up basically involves these steps:

1. Setup `devise` or another form of authentication
1. Setup `doorkeeper`, optionally in combination with `warden-doorkeeper`
1. Setup `doorkeeper-openid_connect`
1. Create one or more Doorkeeper applications with the `openid` scope included, and configure your clients with them

> Is it possible to use existing session state if the user is already logged in?

Hmm neither Doorkeeper or this extension deals directly with sessions, it's basically just an authentication API and any handling of session state will happen in your client application ("Relying Party" in OIC terms).

Maybe I misunderstood, could you elaborate on what the client side looks like?

> Which part of this is responsible for rendering the view wherein the user (post-authentication) is presented with the requested scopes/claims and accepts or rejects the authorization request?

That's Doorkeeper, see [Customizing views](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-views) and [this caveat for nonces](https://github.com/doorkeeper-gem/doorkeeper-openid_connect#nonces).

> Finally, is a migration on the user to store some sort of subject identifier required or is there a property on the user object provided by doorkeeper already that can be coopted into this role?

No, you have to define how to get the identifier with the `subject` callback, see [README](https://github.com/doorkeeper-gem/doorkeeper-openid_connect#configuration)

> Thank you very much!

You're welcome! I tweaked the README a bit, let me know which parts are still unclear.

Doorkeeper also has an [extensive wiki](https://github.com/doorkeeper-gem/doorkeeper/wiki)) and [example applications](https://github.com/doorkeeper-gem/doorkeeper/wiki/Example-Applications).

**Comment by malacalypse** [comment]
Great, thanks. I'll take a look and come back with clarifications/questions. Great to see some support for this gem, much appreciated!

**Comment by malacalypse** [comment]
Ok, great, I think we have this mostly figured out.

Only question remaining is: when auto-discovering my openid connect endpoint, the /oauth/ prefix is not being attempted by the client. I was under the impression that auto-discovery should include this; do I need to tell the client explicitly to use this or is there some configuration I need to set up?

**Comment by toupeira** [comment]
@malacalypse gotcha :)

Just for reference, the routes added by this gem are described in the [README](https://github.com/doorkeeper-gem/doorkeeper-openid_connect#routes), and I just added a link to the [Doorkeepr wiki](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-routes#version--05-1) for details on how to customize them.
