### ISSUE TITLE
DONT mention omniauth-openid-connect

### ISSUE THREAD

**Issue by aisensiy** [doorkeeper-gem/doorkeeper-openid_connect#37]
This repository seems abandoned for a long time, hope to give some new solution.

**Comment by toupeira** [comment]
Looks like there's some maintenance going on at https://github.com/m0n9oose/omniauth_openid_connect, maybe you want to help them? Also see https://github.com/jjbohn/omniauth-openid-connect/issues/67

I've changed the link in the README.
