### ISSUE TITLE
HELP WANTED Failed to get the id_token

### ISSUE THREAD

**Issue by aisensiy** [doorkeeper-gem/doorkeeper-openid_connect#38]
Here is the response from `POST /oauth/token` and there is no `id_token` return.

```
{
    "access_token": "9ca3ef6856061bf122e74c25d420430b348b279acd302c1b60f92ae498a92d08",
    "token_type": "bearer",
    "expires_in": 7200,
    "scope": "profile id_token email",
    "created_at": 1499966549
}
```

BTW I can not get `/oauth/userinfo` with HEADER `Authoraztion: Bearer MY_ACCESS_TOKEN` why is that?

My repo is [https://github.com/aisensiy/uaa](https://github.com/aisensiy/uaa).

**Comment by toupeira** [comment]
It looks like you're missing the `openid` scope, there is no `id_token`
scope defined in the standard.

**Comment by aisensiy** [comment]
Thanks for you quick reply. I really appreciate that.

And...another quick question...

![image](https://user-images.githubusercontent.com/661860/28199748-9d34ccb6-689a-11e7-8415-18c1e46c239f.png)
I am trying to create a sso solution with this can I skip the default authenticate page by configuration?

**Comment by aisensiy** [comment]
Thanks for you reply. I really appreciate it.
