### ISSUE TITLE
Ruby < 2.3 support.

### ISSUE THREAD

**Issue by nashby** [doorkeeper-gem/doorkeeper-openid_connect#50]
Current version of `json-jwt` gem supports Ruby >= 2.3 https://github.com/nov/json-jwt/blob/master/json-jwt.gemspec#L14. That's the reason why Travis is failing with older rubies. There's two options: 1. lock `json-jwt` version that supports older rubies 2. drop support for Ruby < 2.3. 

@toupeira what do you think?

**Comment by toupeira** [comment]
@nashby thanks! I'm definitely for staying with latest versions, especiallly with security-sensitive libs. Also [looks like Ruby 2.2 is EOL soon anyway](https://www.ruby-lang.org/en/downloads/branches/).

I've dropped support for Ruby < 2.3 now in https://github.com/doorkeeper-gem/doorkeeper-openid_connect/commit/3202fdf6c312e02ad8baafc2d14a31bb4b537e9f
