### ISSUE TITLE
grant type password

### ISSUE THREAD

**Issue by hszeto** [doorkeeper-gem/doorkeeper-openid_connect#53]
How can I implement openid with password grant type?

**Comment by toupeira** [comment]
Do you mean the [resource owner password credentials flow](https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Resource-Owner-Password-Credentials-flow)? Doorkeeper supports that, but we're probably missing some plumbing in this gem. Let me know if it works, otherwise PRs are welcome :)

**Comment by hszeto** [comment]
I got it. Need to pass in the client id.

POST to`/oauth/token` with body:
```
{
	"grant_type": "password",
	"username": "test@example.com",
	"password": "abc123",
	"client_id": "123456789abcdefg",
	"scope":"openid"
}
```
