### ISSUE TITLE
Compatibility with Doorkeeper 5.0.0rc1?

### ISSUE THREAD

**Issue by molenick** [doorkeeper-gem/doorkeeper-openid_connect#54]
Hi, thanks for the great work on this gem.  I'm trying to gauge how compatible a recent version of this gem might be with Doorkeeper 5.0.0rc1.  I know there's probably not good support for it since it's an RC, but I wanted to ask what options I might have.  I'm pinned to rc1 because I need PKCE for my project.

Thanks!

**Comment by nashby** [comment]
@molenick Hey! I haven't tested it either. Would you mind to try it out and report back if you have any compatibility issues? Thanks!

**Comment by toupeira** [comment]
@nashby thanks for the PR! :+1: 

@molenick please give it a try with version 1.5.1

**Comment by toupeira** [comment]
@molenick actually try 1.5.2, 1.5.1 had some breakage ;-)

**Comment by molenick** [comment]
@toupeira Thanks!
