### ISSUE TITLE
NoMethodError at /oauth/authorize/native with doorkeeper 5.0

### ISSUE THREAD

**Issue by nhosoya** [doorkeeper-gem/doorkeeper-openid_connect#57]
I noticed that native_oauth_authorization_path( `/oauth/authorize/native` ) returns the error :
> undefined method `application' for nil:NilClass

at [here](https://github.com/doorkeeper-gem/doorkeeper/blob/4c94445c4508cb372bc2004e74353b525359af46/lib/doorkeeper/oauth/pre_authorization.rb#L58).
This occurs only with `doorkeeper 5.0`.

-- 
Probably caused by this changes.
https://github.com/doorkeeper-gem/doorkeeper/pull/1088/commits/698fba0d21b457be9778e6d7a73ddbb3b8ce2486

**Comment by toupeira** [comment]
Thanks for the report!

What version of `doorkeeper-openid_connect` are you on? Does this still happen with 1.5.2?

Also, can you describe how to reproduce the error?

**Comment by nhosoya** [comment]
This error is reproduced with
```
ruby 2.5.1
rails 5.2.1
doorkeeper 5.0.0
doorkeeper-openid_connect 1.5.2
```

I created minimum repository to reproduce this.
https://github.com/nhosoya/doorkeeper-openid_connect-sample

Steps to reproduce:
1. Create new oauth application that redirect_uri is `urn:ietf:wg:oauth:2.0:oob`.
2. Access to Authorization Endpoint for this application and authorize.
(Or access directly `/oauth/authorize/native?code=aaa`)

Only doorkeeper(without doorkeeper-openid_connect), this error is not reproduced.
https://github.com/nhosoya/doorkeeper-openid_connect-sample/tree/only-doorkeeper

**Comment by arianvp** [comment]
I'm running into exactly the same issue.

**Comment by atomiyama** [comment]
https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/6829c5881067cb6289263705576c31cd1b6c21c7/lib/doorkeeper/openid_connect/helpers/controller.rb#L10

i think this line should  be changed like below
```
next unless pre_auth&.scopes&.include? 'openid' 
```

**Comment by toupeira** [comment]
Apologies for the long delay, and happy new year everyone! :grin: 

I'm not really sure how the native authorization works, but https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/60 should fix the exception.

Please try again with the new version 1.5.3.

**Comment by nhosoya** [comment]
It works fine. Thank you, and happy new year! 😃
