### ISSUE TITLE
RP-Initiated Logout

### ISSUE THREAD

**Issue by camilo0365** [doorkeeper-gem/doorkeeper-openid_connect#73]
Are there any plans to support RP initiated logout as per the Spec?

https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

Thanks!

**Comment by toupeira** [comment]
@camilo0365 no plans from my side, but PRs are always welcome! :)

**Comment by ralph** [comment]
I don't know if it satisfies the spec, but I just created a PR to support `end_session_endpoint`. For https://github.com/IdentityModel/oidc-client-js, that's enough to work correctly. It will trigger client side hooks and then redirect to the specified url. Check it out here:

https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/103

**Comment by toupeira** [comment]
@ralph thanks! :raised_hands: 

This is now released in 1.7.2 so I'll close this issue.

/cc @nbulaj

**Comment by rodrigocvb** [comment]
@ralph do you know if this change adds support to post_logout_redirect_uri as specified in section 3, "Redirection to RP After Logout", of this spec?

https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout

I'm using oidc-client-js and trying to redirect the user back to the frontend after logout. But I'm not able to do so.

I even updated from 1.7.1 to 1.7.2, but for now I'm facing a circular dependency issue. If my problem (the post_logout_redirect_uri thing) is not solved with this new version, I'm not planning to follow with this update. Thanks!

**Comment by ralph** [comment]
Hi @rodrigocvb! No, this only adds support for `end_session_endpoint`, not for `post_logout_redirect_uris`, I'm afraid.

But maybe you want to open another PR to add this? Implementation should be very similar to #103.

**Comment by yoonwaiyan** [comment]
@ralph I've read #103 but I don't see any implementation being done on `end_session_endpoint` other than allowing users to define it with their own route handling, and your example provided a Devise logout URL, so Doorkeeper will not handle the logout flow as specified in the specs?

**Comment by maleonix** [comment]
Hello, 

I've use end_session_endpoint  and post_logout_redirect_uri in my project (SSO+ RubyOnRails API) + Client React


end_session_endpoint  =>  http://doorkepper.com/auth/sign_out
post_logout_redirect_uri =>  http://client.com
ENV["HOST"] =>   http://doorkepper.com

Add in `doorkeeper_openid_connect.rb`
```
  end_session_endpoint do
    Rails.application.routes.url_for({ host:  ENV["HOST"] }, :destroy_user_session)
  end
  subject do |resource_owner|
    # Example implementation:
    resource_owner.id
  end
```

Add in `sessions_controller.rb`
```
  def after_sign_out_path_for(resource)
    postLogoutRedirectUri = params["post_logout_redirect_uri"]
    postLogoutRedirectUri
  end
```

Add in oidc-client.js client app

```
    post_logout_redirect_uri: `${config.uri.local}`,
    metadata: {
      authorization_endpoint: `${config.uri.auth}/oauth/authorize`,
      token_endpoint: `${config.uri.auth}/oauth/token`,
      end_session_endpoint: `${config.uri.auth}/auth/sign_out`,
    },
```
