### ISSUE TITLE
Using and add dependency jwt instead of json-jwt

### ISSUE THREAD

**Issue by phlegx** [doorkeeper-gem/doorkeeper-openid_connect#74]
Hi!

Is there any reason why this gem uses `json-jwt` gem dependency instead of `jwt` gem?
The `jwt` gem is more complete and has a big community ([jwt.io](https://jwt.io/)). For example gem `doorkeeper-jwt` uses gem `jwt`.

**Comment by toupeira** [comment]
@phlegx not sure, when I originally added `json-jwt` in 2016 I think there was some functionality I was missing in the `jwt` gem.

In case you're already familiar with `jwt`, do you want to submit a PR? We only have four locations where `json-jwt` is used (grep for `JSON::`) so it should be fairly straightforward. If not I'll give it a try, but might take a while until I get around to it ;-)

**Comment by phlegx** [comment]
Here you can see the differences:

![Screenshot_2020-01-20 JWT IO](https://user-images.githubusercontent.com/111506/72758750-fb641580-3bd3-11ea-971b-375700f786af.png)

Gem `jwt` supports more verification methods ans has over 2.800 follower and gem `json-jwt` has only 237 follower.

**Comment by phlegx** [comment]
I need to wait for a PR merge and new release of the gem `jwt`. Then I have the code already prepared to move from gem `json-jwt` to `jwt`.

**Comment by kristof-mattei** [comment]
JWK support was missing (until recently) from `jwt`. It now has support for that.

**Comment by phlegx** [comment]
That's true! We have contributed to get JWK on `ruby-jwt` gem. In the next time I will publish a PR for `doorkeeper-openid_connect` with `ruby-jwt`.

**Comment by kristof-mattei** [comment]
See #177

**Comment by codespearhead** [comment]
@phlegx Should this issue be closed now that #177 was merged?
