### ISSUE TITLE
Not passing required parameters results in a 500

### ISSUE THREAD

**Issue by isabellechalhoub** [doorkeeper-gem/doorkeeper-openid_connect#78]
The `Doorkeeper::AuthorizationsController` checks to see whether or not required parameters are present by running `pre_auth.authorizable?` [in the `new` action](https://github.com/doorkeeper-gem/doorkeeper/blob/03b1437c6bda10ec74c256b4f8c5c3d98b4e5227/app/controllers/doorkeeper/authorizations_controller.rb#L7).

This gem modifies the behavior of the `:authenticate_resource_owner!` before filter that runs prior to the `new` action.  One of the modifications is to inspect the `pre_auth` object (an instance of `OAuth::PreAuthorization`) and [look at its `scopes`](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/17dbe9517e855ed46d6b8dec3a311e093933e34e/lib/doorkeeper/openid_connect/helpers/controller.rb#L11).

The `OAuth::PreAuthorization#scopes` method in turn fires the [`build_scopes` private method](https://github.com/doorkeeper-gem/doorkeeper/blob/03b1437c6bda10ec74c256b4f8c5c3d98b4e5227/lib/doorkeeper/oauth/pre_authorization.rb#L59), which calls `client.application.scopes`.  This method assumes that `client` is present.  However, if you do not initialize the object with `@client`, it obviously blows up.  This has not been an issue in Doorkeeper itself, because usually the `OAuth::PreAuthorization` object is assumed to be valid.  However, this OpenID Connect gem inspects the object before it has been validated.

We have a PR to add a validation check before trying to inspect the scopes.

**Comment by toupeira** [comment]
Thanks again, you can give this a try with the new version 1.6.2.
