### ISSUE TITLE
Support Doorkeeper 5.2

### ISSUE THREAD

**Issue by toupeira** [doorkeeper-gem/doorkeeper-openid_connect#88]
Doorkeeper 5.2 introduced some breaking changes, see https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/83

This is now being worked on in https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/85

**Comment by byu** [comment]
Just wondering if there is an ETA on 5.2 support? Thanks!

**Comment by toupeira** [comment]
@byu sorry I can't give you an ETA, will take me a while until I find some time to look into this.

Any help is welcome though! IIRC the existing PR https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/85 is mostly there for Doorkeeper 5.2 support, and Rails 6 support could also be added in another PR.
