### ISSUE TITLE
Is the form_post response_mode supported?

### ISSUE THREAD

**Issue by yourtallness** [doorkeeper-gem/doorkeeper-openid_connect#92]
It is my understanding that if the response type is `form_post` the OP will POST the response instead of encoding the id_token (etc) in the query string or fragment.

I can't find evidence of it being supported by looking at the source code.

Please advise, TIA.

**Comment by toupeira** [comment]
@yourtallness `response_type=form_post` doesn't seem to be supported by the Doorkeeper gem, and unless I'm missing something this would need to be implemented there first. Afterwards we probably need some support in this gem as well, to add the ID token to that response.

Can you open an issue at https://github.com/doorkeeper-gem/doorkeeper?

**Comment by linhdangduy** [comment]
@yourtallness It takes quite long time, but both doorkeeper (v5.5.0) and doorkeeper-openid_connect (v1.8.0.pre.rc1 prerelease) already support `response_mode`
