### ISSUE TITLE
Confusion about signing_key

### ISSUE THREAD

**Issue by yourtallness** [doorkeeper-gem/doorkeeper-openid_connect#93]
Hello,

I am a bit confused about the signing key.

I understand that only the private key needs to be provided in the config because the public key can be generated from the private one.

However shouldn't the public key be provided to the client application so that it can verify the JWS signature?

~Additionally, if we are not using the implicit flow that returns the `id_token` (e.g. we use the authorization code flow only), we can skip this configuration, correct?~

Turns out the gem requires the signing_key even if no `id_token` is being requested.

TIA

**Comment by toupeira** [comment]
@yourtallness the public key is provided to clients through the [OIDC discovery mechanism](https://openid.net/specs/openid-connect-discovery-1_0.html), specifically through the standardized `/.well-known/openid-configuration` endpoint which points to our custom `/oauth/discovery/keys` endpoint (see https://github.com/doorkeeper-gem/doorkeeper-openid_connect#routes).

> ~Additionally, if we are not using the implicit flow that returns the id_token (e.g. we use the authorization code flow only), we can skip this configuration, correct?~
>
> Turns out the gem requires the signing_key even if no id_token is being requested.

Not sure I follow, AFAIK an ID token is always returned in some form when the `openid` scope is requested. If that scope is not included, this gem shouldn't become active and you're dealing with a normal OAuth flow from the Doorkeeper gem.

**Comment by yourtallness** [comment]
I mean that we don't use the implicit flow that returns the `id_token`.

Our clients will be hitting the userinfo endpoint to obtain the user information.

**Comment by toupeira** [comment]
@yourtallness ok thanks I was confused, I checked the specs and it's possible to send a request with `response_type=code` where no ID token is returned: https://openid.net/specs/openid-connect-core-1_0.html#Authentication

Can you post the exact error you're running into?

I'm wondering if it would be sufficient to specify `nil` as default for `signing_key` in `Doorkeeper::OpenidConnect::Config`: https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/13b77d546dd3648ff7dfb3a6b2584829ead7421a/lib/doorkeeper/openid_connect/config.rb#L100 (if you could quickly verify, that would be also great!)

**Comment by yourtallness** [comment]
Turns out the client had to interface with actually required the i_ token to be included in the access_token response, so the use case in the original post is now not applicable to us.

FWIW, I set the `signing_key` to `nil` and it worked.
Thanks for the support!
