### ISSUE TITLE
Permission denied in rvm when running a single test in Rubymine

### ISSUE THREAD

**Issue by yourtallness** [doorkeeper-gem/doorkeeper-openid_connect#94]
Rubymine tries to execute the following command:

`/bin/zsh -c "bash -c '/Users/mark/.rvm/bin/rvm ruby-2.4.2 do /Users/mark/Dev/b2bwave/bin/bundle exec /Users/mark/.rvm/rubies/ruby-2.4.2/bin/ruby -Itest /Users/mark/Dev/b2bwave/test/controllers/api_customer/orders_controller_test.rb'"`

This results in:

```
/Users/mark/.rvm/scripts/set: line 19: /Users/mark/Dev/b2bwave/bin/bundle: Permission denied
/Users/mark/.rvm/scripts/set: line 19: exec: /Users/mark/Dev/b2bwave/bin/bundle: cannot execute: Undefined error: 0
```

I have never encountered permissions issues with rvm on multiple installations.

Please advise.

Mark

**Comment by toupeira** [comment]
@yourtallness sorry this looks like a general problem with your RVM/Bundler setup and unrelated to this gem. Maybe try reinstalling the `bundler` gem?

**Comment by anatoliyarkhipov** [comment]
@yourtallness Have you figured that out? I'm having precisely the same issue.

**Comment by yourtallness** [comment]
@anatoliyarkhipov I'm afraid I ended up making the binaries executable and be done with it. 😞

**Comment by anatoliyarkhipov** [comment]
@yourtallness This one `/Users/mark/Dev/b2bwave/bin/bundle`? 🤔

**Comment by jippylong12** [comment]
For anyone seek answers, I used [this link](https://askubuntu.com/questions/709439/getting-permission-denied-when-running-bundler-command) to resolve the issue. 

Essentially the bundle file needs to be given sudo permissions. In the case of the OP, it would be

`sudo chmod +x /Users/mark/Dev/b2bwave/bin/bundle`

Take the path that is in the Permission Denied line and add it after sudo chmod +x. Once you do that, you will be able to run Rspec.
